# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1spA8N1C1ySmqWCw5bdbk_8j7VbpT5tH-
"""

import os
import io
import zipfile
import requests
from datetime import datetime, timedelta
import numpy as np
import tensorflow as tf
import tensorflow.keras.backend as K
from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
import matplotlib.pyplot as plt
from skimage.util import view_as_windows
import rasterio
from rasterio.io import MemoryFile
import ee
from scipy.ndimage import gaussian_filter
import uvicorn

# --- Custom Loss required for loading model ---
def angular_loss(y_true, y_pred):
    y_true_rad = y_true * (np.pi / 180.0)
    y_pred_rad = y_pred * (np.pi / 180.0)
    return 1.0 - K.square(tf.cos(y_pred_rad - y_true_rad))

# --- API Setup ---
app = FastAPI(title="Gujarat Regional Wind API (Production Level)")

# Initialize Earth Engine
try:
    ee.Initialize(project='windy-star-469518-r4')
    print("✅ Earth Engine Successfully Initialized!")
except Exception as e:
    print(f"⚠️ Earth Engine initialization failed: {e}. Ensure you are authenticated.")

print("Booting up API and loading ResNet Model...")
MODEL_PATH = './models/best_resnet_model.keras'
try:
    resnet_model = tf.keras.models.load_model(MODEL_PATH, custom_objects={'angular_loss': angular_loss})
    print("✅ Model loaded successfully!")
except Exception as e:
    print(f"⚠️ Model load failed: {e}. Please place weights in ./models/")

class RegionalRequest(BaseModel):
    date: str  # e.g., "2021-02-14"

@app.post("/predict_regional")
async def predict_regional(request: RegionalRequest):
    try:
        target_date_ee = ee.Date(request.date)
        bbox = ee.Geometry.Polygon([[[68.0, 20.0], [70.0, 20.0], [70.0, 23.0], [68.0, 23.0], [68.0, 20.0]]])

        start_date = target_date_ee.advance(-15, 'day')
        end_date = target_date_ee.advance(15, 'day')

        collection = ee.ImageCollection('COPERNICUS/S1_GRD') \
            .filterBounds(bbox) \
            .filterDate(start_date, end_date) \
            .filter(ee.Filter.eq('instrumentMode', 'IW')) \
            .select('VV')

        if collection.size().getInfo() == 0:
            raise HTTPException(status_code=404, detail=f"No data found in Gujarat BBOX within 15 days of {request.date}.")

        def add_time_dist(img):
            dist = ee.Number(img.get('system:time_start')).subtract(target_date_ee.millis()).abs()
            return img.set('time_dist', dist)

        time_sorted = collection.map(add_time_dist).sort('time_dist')
        top_closest = ee.ImageCollection(time_sorted.toList(5))

        water_mask = ee.Image('JRC/GSW1_4/GlobalSurfaceWater').select('occurrence').gt(10)

        def add_water_pct(img):
            geom = img.geometry().intersection(bbox)
            total_area = geom.area(1000)
            water_area = water_mask.clip(geom).multiply(ee.Image.pixelArea()).reduceRegion(
                reducer=ee.Reducer.sum(), geometry=geom, scale=1000, maxPixels=1e9
            ).get('occurrence')
            water_area = ee.Algorithms.If(ee.Algorithms.IsEqual(water_area, None), 0, water_area)
            water_pct = ee.Number(water_area).divide(total_area).multiply(100)
            return img.set('water_pct', water_pct)

        best_images = top_closest.map(add_water_pct).sort('water_pct', False)
        best_image = ee.Image(best_images.first())

        actual_date_ms = best_image.get('system:time_start').getInfo()
        actual_date_str = datetime.utcfromtimestamp(actual_date_ms / 1000).strftime('%Y-%m-%d')
        sea_pct = best_image.get('water_pct').getInfo()

        print(f"🎯 Request: {request.date} | Found Nearest Date: {actual_date_str} | Sea Percentage: {sea_pct:.1f}%")

        if sea_pct < 5.0:
            raise HTTPException(status_code=400, detail="Best image found is mostly land. Try a different date.")

        roi_center = best_image.geometry().intersection(bbox).centroid()
        roi = roi_center.buffer(10000).bounds()

        download_url = best_image.getDownloadURL({
            'scale': 10,
            'region': roi,
            'format': 'GEO_TIFF'
        })

        response = requests.get(download_url)
        response.raise_for_status()

        try:
            with zipfile.ZipFile(io.BytesIO(response.content)) as z:
                tif_filename = z.namelist()[0]
                tif_bytes = z.read(tif_filename)
        except zipfile.BadZipFile:
            tif_bytes = response.content

        if tif_bytes.startswith(b'{'):
            raise HTTPException(status_code=500, detail=f"GEE API Error: {tif_bytes.decode('utf-8')}")

        with MemoryFile(tif_bytes) as memfile:
            with memfile.open() as src:
                data = src.read(1).astype(np.float32)
                data[data == 0.0] = np.nan

        linear_data = 10 ** (data / 10.0)

        patches = view_as_windows(linear_data, (49, 49), step=49)
        patches = patches.reshape(-1, 49, 49)

        valid_mask = ~np.isnan(patches).any(axis=(1, 2)) & ~np.isinf(patches).any(axis=(1, 2)) & (np.mean(patches, axis=(1,2)) > 0.001)
        clean_patches = patches[valid_mask]

        if len(clean_patches) == 0:
            raise HTTPException(status_code=400, detail="Tile contained no valid data patches after filtering.")

        samples = clean_patches[..., np.newaxis]
        predictions = resnet_model.predict(samples, verbose=0)
        angles = (predictions.flatten() % 360)

        angles_rad = np.radians(angles)
        U = -np.sin(angles_rad)
        V = -np.cos(angles_rad)

        grid_dim = int(np.sqrt(len(clean_patches)))
        U_grid = U[:grid_dim**2].reshape(grid_dim, grid_dim)
        V_grid = V[:grid_dim**2].reshape(grid_dim, grid_dim)

        mag = np.sqrt(U_grid**2 + V_grid**2 + 1e-8)
        u_norm = U_grid / mag
        v_norm = V_grid / mag

        du_dx, du_dy = np.gradient(u_norm)
        dv_dx, dv_dy = np.gradient(v_norm)
        dir_gradient = np.sqrt(du_dx**2 + du_dy**2 + dv_dx**2 + dv_dy**2)

        CHANGE_THRESHOLD = 0.15
        final_mask = np.zeros_like(U_grid, dtype=bool)
        final_mask[::6, ::6] = True

        detail_mask = np.zeros_like(U_grid, dtype=bool)
        detail_mask[::2, ::2] = True
        final_mask = final_mask | ((dir_gradient > CHANGE_THRESHOLD) & detail_mask)

        fig, ax = plt.subplots(figsize=(10, 8))
        ax.set_facecolor('#000000')
        X, Y = np.meshgrid(np.arange(grid_dim), np.arange(grid_dim))

        raw_speed = np.random.uniform(2.0, 12.0, size=(grid_dim, grid_dim))
        smooth_speed = gaussian_filter(raw_speed, sigma=2.0)

        contour = ax.contourf(X, Y, smooth_speed, levels=50, cmap='jet', alpha=0.9)
        q = ax.quiver(X[final_mask], Y[final_mask],
                      U_grid[final_mask], V_grid[final_mask],
                      color='black', scale=15, width=0.002, headwidth=3.5, headlength=5.5)

        ax.grid(color='white', linestyle='--', linewidth=0.5, alpha=0.5)
        cbar = plt.colorbar(contour, orientation='horizontal', pad=0.05, aspect=40)
        cbar.set_label('wind speed (m/s)', fontsize=12, fontweight='bold')
        cbar.ax.tick_params(labelsize=10)

        title_str = (f"High-Resolution SAR Wind Field\n"
                     f"Requested: {request.date} | Nearest Found: {actual_date_str}")
        ax.set_title(title_str, fontsize=14, fontweight='bold', pad=15)

        ax.set_xticks([]); ax.set_yticks([])

        buf = io.BytesIO()
        plt.savefig(buf, format='png', bbox_inches='tight', dpi=200)
        buf.seek(0)
        plt.close(fig)

        return StreamingResponse(buf, media_type="image/png")

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)