# -*- coding: utf-8 -*-
"""cec-trial1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/114-bBcla39XZDN6KHNnodpeGB7m3utnU
"""

from google.colab import drive
import os

# 1. Mount the Drive
drive.mount('/content/drive')

from google.colab import drive
import os

# 2. Check the exact folder path
SOURCE_DIR = '/content/drive/MyDrive/S1_Wind_Project'

if os.path.exists(SOURCE_DIR):
    files = os.listdir(SOURCE_DIR)
    tif_files = [f for f in files if f.endswith('.tif')]
    print(f"\n✅ SUCCESS! Found the folder. It contains {len(tif_files)} .tif files.")
else:
    print(f"\n❌ ERROR: The folder '{SOURCE_DIR}' does not exist.")
    print("Here are the folders actually sitting in your main Drive:")
    # This prints out your main Drive folders so you can find the correct name
    print(os.listdir('/content/drive/MyDrive/'))

from google.colab import drive
import os

# 1. Mount the Drive
drive.mount('/content/drive')

import os
import glob
import rasterio
import numpy as np
from scipy import ndimage
import gc

# --- Configuration ---
INPUT_DIR = '/content/drive/MyDrive/S1_Wind_Project'
OUTPUT_DIR = '/content/drive/MyDrive/S1_Processed_Patches'
os.makedirs(OUTPUT_DIR, exist_ok=True)

TARGET_IMAGES = 15
PATCH_SIZE = 49
STRIDE = 20

def extract_and_clean_patches(vv_data, water_mask):
    """Slices the array into 49x49 patches and cleans land pixels."""
    h, w = vv_data.shape
    file_patches = []

    for y in range(0, h - PATCH_SIZE, STRIDE):
        for x in range(0, w - PATCH_SIZE, STRIDE):
            patch_vv = vv_data[y:y+PATCH_SIZE, x:x+PATCH_SIZE]
            patch_water = water_mask[y:y+PATCH_SIZE, x:x+PATCH_SIZE]

            land_percentage = np.sum(patch_water == 0) / (PATCH_SIZE * PATCH_SIZE)

            if land_percentage > 0.25:
                continue

            if 0.0 < land_percentage <= 0.25:
                invalid = (patch_water == 0)
                indices = ndimage.distance_transform_edt(invalid, return_distances=False, return_indices=True)
                patch_vv[invalid] = patch_vv[tuple(indices[:, invalid])]
                patch_vv[invalid] += np.random.normal(0, 0.1, np.sum(invalid))

            mean_val, std_val = np.mean(patch_vv), np.std(patch_vv)
            norm_patch = (patch_vv - mean_val) / (std_val + 1e-8)
            file_patches.append(norm_patch.astype(np.float32))

    return file_patches

# --- Execution ---
all_tifs = glob.glob(os.path.join(INPUT_DIR, "*.tif"))
print(f"Scanning for {TARGET_IMAGES} valid images...")

successful_images = 0

for tiff_path in all_tifs:
    if successful_images >= TARGET_IMAGES:
        print("\n✅ Target reached! All necessary data is processed.")
        break

    try:
        # 1. Attempt to open and read (skips corrupted files)
        with rasterio.open(tiff_path) as src:
            vv_data = src.read(1)
            water_mask = src.read(2)

        # 2. Check global water percentage
        sea_ratio = np.sum(water_mask == 1) / water_mask.size

        # 3. If it has enough ocean, extract patches
        if sea_ratio > 0.15:
            print(f"Processing {os.path.basename(tiff_path)} (Sea: {sea_ratio*100:.1f}%)")
            patches = extract_and_clean_patches(vv_data, water_mask)

            if len(patches) > 0:
                # Save immediately to bypass RAM limits
                save_path = os.path.join(OUTPUT_DIR, f'patches_img_{successful_images}.npy')
                np.save(save_path, np.array(patches))
                print(f"  -> Saved {len(patches)} patches.")

                successful_images += 1

            # Clean up memory
            del patches, vv_data, water_mask
            gc.collect()

    except Exception as e:
        # Silently skip the corrupted files GEE left behind
        pass

if successful_images < TARGET_IMAGES:
    print(f"\n⚠️ Finished scanning all files, but only found {successful_images} valid images.")

import os
import glob
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
import gc
from google.colab import drive

# 1. Mount the Drive
drive.mount('/content/drive')

# --- Configuration ---
INPUT_DIR = '/content/drive/MyDrive/S1_Processed_Patches'
TARGET_BASE_PATCHES = 78000

npy_files = glob.glob(os.path.join(INPUT_DIR, "*.npy"))
print(f"Found {len(npy_files)} files. Loading incrementally to save RAM...")

# Calculate how many patches we need from each file
target_per_file = TARGET_BASE_PATCHES // max(1, len(npy_files))
sampled_patches = []

# --- 1. Incremental Memory-Safe Loading ---
for i, file in enumerate(npy_files):
    # Load ONLY one file into memory
    data = np.load(file).astype(np.float32)

    # Sample it immediately to reduce size
    if len(data) > target_per_file:
        np.random.seed(42 + i)
        indices = np.random.choice(len(data), target_per_file, replace=False)
        data = data[indices]

    # Store the tiny sample
    sampled_patches.append(data)

    # Nuke the original large array from RAM before opening the next one
    del data
    gc.collect()
    print(f"Processed file {i+1}/{len(npy_files)}...")

# Combine the tiny samples into one array
base_patches = np.concatenate(sampled_patches, axis=0)
del sampled_patches
gc.collect()

print(f"\nSuccessfully loaded {len(base_patches)} base patches. Memory is safe!")

# --- 2. Mock Ground Truth ---
# (Replace this with real ECMWF angles later)
targets = np.random.uniform(0, 360, len(base_patches)).astype(np.float32)

# --- 3. Split Base Data ---
print("Splitting base data...")
X_base_train, X_base_val, y_base_train, y_base_val = train_test_split(
    base_patches, targets, test_size=0.10, random_state=42
)

del base_patches, targets
gc.collect()

# --- 4. The On-The-Fly Memory-Safe Generator ---
class WindDataGenerator(tf.keras.utils.Sequence):
    def __init__(self, base_x, base_y, batch_size=16):
        # A base batch of 16 will yield an augmented batch of 96 to the GPU
        self.base_x = base_x
        self.base_y = base_y
        self.batch_size = batch_size
        self.indices = np.arange(len(self.base_x))
        np.random.shuffle(self.indices)

    def __len__(self):
        return int(np.ceil(len(self.base_x) / self.batch_size))

    def __getitem__(self, index):
        batch_idx = self.indices[index * self.batch_size : (index + 1) * self.batch_size]
        batch_x = self.base_x[batch_idx]
        batch_y = self.base_y[batch_idx]

        aug_x, aug_y = [], []
        for patch, angle in zip(batch_x, batch_y):
            p_exp = patch[..., np.newaxis]
            aug_x.append(p_exp)
            aug_y.append(angle)
            for k in [1, 2, 3]:
                aug_x.append(np.rot90(p_exp, k=k))
                aug_y.append((angle - 90 * k) % 360)
            aug_x.append(np.fliplr(p_exp))
            aug_y.append((360 - angle) % 360)
            aug_x.append(np.flipud(p_exp))
            aug_y.append((180 - angle) % 360)

        aug_x = np.array(aug_x, dtype=np.float32)
        aug_y = np.array(aug_y, dtype=np.float32)
        shuff_idx = np.arange(len(aug_x))
        np.random.shuffle(shuff_idx)

        return aug_x[shuff_idx], aug_y[shuff_idx]

    def on_epoch_end(self):
        np.random.shuffle(self.indices)

# --- 5. Instantiate Generators ---
train_gen = WindDataGenerator(X_base_train, y_base_train, batch_size=16)
val_gen = WindDataGenerator(X_base_val, y_base_val, batch_size=16)

print("\n✅ Setup Complete! Ready for Step 4 (Model Training)!")

import os
import glob
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
import gc
from google.colab import drive

# 1. Mount the Drive
drive.mount('/content/drive')

# --- Configuration ---
INPUT_DIR = '/content/drive/MyDrive/S1_Processed_Patches'
TARGET_BASE_PATCHES = 78000

npy_files = glob.glob(os.path.join(INPUT_DIR, "*.npy"))
print(f"Found {len(npy_files)} files. Loading and scrubbing NaNs incrementally...")

target_per_file = TARGET_BASE_PATCHES // max(1, len(npy_files))
sampled_patches = []
total_corrupted = 0

# --- 1. Incremental Loading & NaN Scrubbing ---
for i, file in enumerate(npy_files):
    data = np.load(file).astype(np.float32)

    # THE FIX: Hunt down and destroy any patch containing a NaN or Infinity
    # We check across the pixel dimensions (axis 1 and 2)
    valid_mask = ~np.isnan(data).any(axis=(1, 2)) & ~np.isinf(data).any(axis=(1, 2))

    corrupted_count = len(data) - np.sum(valid_mask)
    total_corrupted += corrupted_count

    # Keep only the valid, clean patches
    data = data[valid_mask]

    # Sample down to save memory
    if len(data) > target_per_file:
        np.random.seed(42 + i)
        indices = np.random.choice(len(data), target_per_file, replace=False)
        data = data[indices]

    sampled_patches.append(data)
    del data
    gc.collect()

base_patches = np.concatenate(sampled_patches, axis=0)
del sampled_patches
gc.collect()

print(f"\n🛡️ Scrubbing complete! Destroyed {total_corrupted} corrupted patches.")
print(f"Successfully loaded {len(base_patches)} CLEAN base patches.")

# --- 2. Mock Ground Truth ---
targets = np.random.uniform(0, 360, len(base_patches)).astype(np.float32)

# --- 3. Split Base Data ---
print("Splitting base data...")
X_base_train, X_base_val, y_base_train, y_base_val = train_test_split(
    base_patches, targets, test_size=0.10, random_state=42
)

del base_patches, targets
gc.collect()

# --- 4. The Updated Data Generator ---
class WindDataGenerator(tf.keras.utils.Sequence):
    # Added **kwargs to fix the PyDataset UserWarning
    def __init__(self, base_x, base_y, batch_size=16, **kwargs):
        super().__init__(**kwargs)
        self.base_x = base_x
        self.base_y = base_y
        self.batch_size = batch_size
        self.indices = np.arange(len(self.base_x))
        np.random.shuffle(self.indices)

    def __len__(self):
        return int(np.ceil(len(self.base_x) / self.batch_size))

    def __getitem__(self, index):
        batch_idx = self.indices[index * self.batch_size : (index + 1) * self.batch_size]
        batch_x = self.base_x[batch_idx]
        batch_y = self.base_y[batch_idx]

        aug_x, aug_y = [], []
        for patch, angle in zip(batch_x, batch_y):
            p_exp = patch[..., np.newaxis]
            aug_x.append(p_exp)
            aug_y.append(angle)
            for k in [1, 2, 3]:
                aug_x.append(np.rot90(p_exp, k=k))
                aug_y.append((angle - 90 * k) % 360)
            aug_x.append(np.fliplr(p_exp))
            aug_y.append((360 - angle) % 360)
            aug_x.append(np.flipud(p_exp))
            aug_y.append((180 - angle) % 360)

        aug_x = np.array(aug_x, dtype=np.float32)
        aug_y = np.array(aug_y, dtype=np.float32)
        shuff_idx = np.arange(len(aug_x))
        np.random.shuffle(shuff_idx)

        return aug_x[shuff_idx], aug_y[shuff_idx]

    def on_epoch_end(self):
        np.random.shuffle(self.indices)

# --- 5. Instantiate Generators ---
train_gen = WindDataGenerator(X_base_train, y_base_train, batch_size=16, workers=4, use_multiprocessing=True)
val_gen = WindDataGenerator(X_base_val, y_base_val, batch_size=16, workers=4, use_multiprocessing=True)

print("\n✅ Setup Complete! Ready for Step 4 (Model Training)!")

import xarray as xr
import numpy as np
import pandas as pd
from google.colab import drive

# 1. Mount the Drive
drive.mount('/content/drive')

# --- Configuration ---
ERA5_FILE_PATH = '/content/drive/MyDrive/S1_Wind_Project/era5_gujarat_wind.nc'

print("Loading ERA5 Weather Data...")
weather_ds = xr.open_dataset(ERA5_FILE_PATH)

def get_true_wind_angle(target_date, target_lat, target_lon):
    """
    Queries the ERA5 dataset for a specific time and location,
    and calculates the meteorological wind direction (0-360 degrees).
    """
    try:
        # THE FIX: Changed 'time' to 'valid_time' to match the new Copernicus format
        point_data = weather_ds.sel(
            valid_time=target_date,
            latitude=target_lat,
            longitude=target_lon,
            method="nearest"
        )

        # Extract the U and V vector components
        u_vector = float(point_data['u10'].values)
        v_vector = float(point_data['v10'].values)

        # Calculate Meteorological Wind Direction
        direction = (270 - np.rad2deg(np.arctan2(v_vector, u_vector))) % 360

        # Calculate Wind Speed
        speed = np.sqrt(u_vector**2 + v_vector**2)

        return direction, speed

    except KeyError as e:
        print(f"Error: Could not find exact time/coordinates. Details: {e}")
        return None, None

# --- Testing the Function ---
test_date = '2020-01-08T13:00:00'
test_lat = 22.5
test_lon = 69.5

print(f"\nQuerying ECMWF data for {test_date} at [Lat: {test_lat}, Lon: {test_lon}]...")

true_angle, true_speed = get_true_wind_angle(test_date, test_lat, test_lon)

if true_angle is not None:
    print(f"✅ Success!")
    print(f"True Wind Direction: {true_angle:.1f}°")
    print(f"True Wind Speed:     {true_speed:.1f} m/s")

import os
import glob
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
import gc

# --- Configuration ---
INPUT_DIR = '/content/drive/MyDrive/S1_Processed_Patches'
TARGET_BASE_PATCHES = 78000

npy_files = glob.glob(os.path.join(INPUT_DIR, "*.npy"))
print(f"Found {len(npy_files)} files. Loading and scrubbing NaNs incrementally...")

target_per_file = TARGET_BASE_PATCHES // max(1, len(npy_files))
sampled_patches = []
total_corrupted = 0

# --- 1. Incremental Loading & NaN Scrubbing ---
for i, file in enumerate(npy_files):
    data = np.load(file).astype(np.float32)

    # Hunt down and destroy any patch containing a NaN or Infinity
    valid_mask = ~np.isnan(data).any(axis=(1, 2)) & ~np.isinf(data).any(axis=(1, 2))

    corrupted_count = len(data) - np.sum(valid_mask)
    total_corrupted += corrupted_count

    # Keep only the valid, clean patches
    data = data[valid_mask]

    # Sample down to save memory
    if len(data) > target_per_file:
        np.random.seed(42 + i)
        indices = np.random.choice(len(data), target_per_file, replace=False)
        data = data[indices]

    sampled_patches.append(data)
    del data
    gc.collect()

base_patches = np.concatenate(sampled_patches, axis=0)
del sampled_patches
gc.collect()

print(f"\n🛡️ Scrubbing complete! Destroyed {total_corrupted} corrupted patches.")
print(f"Successfully loaded {len(base_patches)} CLEAN base patches.")

# --- 2. Ground Truth Mapping (Proof of Concept Test) ---
# Setting ALL targets to your real ERA5 angle (11.1 degrees) to prove the network learns physics!
targets = np.full(len(base_patches), 11.1, dtype=np.float32)

# --- 3. Split Base Data ---
print("Splitting base data...")
X_base_train, X_base_val, y_base_train, y_base_val = train_test_split(
    base_patches, targets, test_size=0.10, random_state=42
)

del base_patches, targets
gc.collect()

# --- 4. The Data Generator ---
class WindDataGenerator(tf.keras.utils.Sequence):
    def __init__(self, base_x, base_y, batch_size=16, **kwargs):
        super().__init__(**kwargs)
        self.base_x = base_x
        self.base_y = base_y
        self.batch_size = batch_size
        self.indices = np.arange(len(self.base_x))
        np.random.shuffle(self.indices)

    def __len__(self):
        return int(np.ceil(len(self.base_x) / self.batch_size))

    def __getitem__(self, index):
        batch_idx = self.indices[index * self.batch_size : (index + 1) * self.batch_size]
        batch_x = self.base_x[batch_idx]
        batch_y = self.base_y[batch_idx]

        aug_x, aug_y = [], []
        for patch, angle in zip(batch_x, batch_y):
            p_exp = patch[..., np.newaxis]

            aug_x.append(p_exp)
            aug_y.append(angle)

            for k in [1, 2, 3]:
                aug_x.append(np.rot90(p_exp, k=k))
                aug_y.append((angle - 90 * k) % 360)

            aug_x.append(np.fliplr(p_exp))
            aug_y.append((360 - angle) % 360)
            aug_x.append(np.flipud(p_exp))
            aug_y.append((180 - angle) % 360)

        aug_x = np.array(aug_x, dtype=np.float32)
        aug_y = np.array(aug_y, dtype=np.float32)
        shuff_idx = np.arange(len(aug_x))
        np.random.shuffle(shuff_idx)

        return aug_x[shuff_idx], aug_y[shuff_idx]

    def on_epoch_end(self):
        np.random.shuffle(self.indices)

# --- 5. Instantiate Generators ---
train_gen = WindDataGenerator(X_base_train, y_base_train, batch_size=16, workers=4, use_multiprocessing=True)
val_gen = WindDataGenerator(X_base_val, y_base_val, batch_size=16, workers=4, use_multiprocessing=True)

print("\n✅ Setup Complete! Ready for Step 4 (Model Training)!")

import xarray as xr
import numpy as np

# Load your ERA5 data
ERA5_FILE_PATH = '/content/drive/MyDrive/S1_Wind_Project/era5_gujarat_wind.nc'
weather_ds = xr.open_dataset(ERA5_FILE_PATH)

# The coordinates from your bounding box
lat, lon = 22.5, 69.5

# The chronological timeline of your 15 processed images
image_timeline = [
    '2020-01-01T01:00:00', # img_0
    '2020-01-03T01:00:00', # img_1
    '2020-01-03T01:00:00', # img_2
    '2020-01-08T01:00:00', # img_3
    '2020-01-03T01:00:00', # img_4
    '2020-01-08T01:00:00', # img_5
    '2020-01-10T13:00:00', # img_6
    '2020-01-08T01:00:00', # img_7
    '2020-01-13T01:00:00', # img_8
    '2020-01-15T01:00:00', # img_9
    '2020-01-15T01:00:00', # img_10
    '2020-01-15T01:00:00', # img_11
    '2020-01-20T01:00:00', # img_12
    '2020-01-20T01:00:00', # img_13
    '2020-01-22T13:00:00'  # img_14
]

print("Extracting true wind angles from ERA5...\n")
file_to_angle_map = {}

for i, target_date in enumerate(image_timeline):
    point_data = weather_ds.sel(valid_time=target_date, latitude=lat, longitude=lon, method="nearest")
    u_vector = float(point_data['u10'].values)
    v_vector = float(point_data['v10'].values)
    direction = (270 - np.rad2deg(np.arctan2(v_vector, u_vector))) % 360

    # Map the index to the calculated angle
    file_to_angle_map[i] = round(direction, 2)

print("✅ Extraction Complete! Copy this dictionary into your Step 3 script:\n")
print("ANGLE_DICT =", file_to_angle_map)

import os
import glob
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
import gc

# --- Configuration ---
INPUT_DIR = '/content/drive/MyDrive/S1_Processed_Patches'
TARGET_BASE_PATCHES = 78000

# ⚠️ PASTE THE DICTIONARY FROM SCRIPT 1 HERE:
ANGLE_DICT = {0: np.float64(26.92), 1: np.float64(25.28), 2: np.float64(25.28), 3: np.float64(16.99), 4: np.float64(25.28), 5: np.float64(16.99), 6: np.float64(38.82), 7: np.float64(16.99), 8: np.float64(260.79), 9: np.float64(47.87), 10: np.float64(47.87), 11: np.float64(47.87), 12: np.float64(52.43), 13: np.float64(52.43), 14: np.float64(35.51)} # Replace this line entirely!

npy_files = glob.glob(os.path.join(INPUT_DIR, "*.npy"))
print(f"Loading files and applying real physics targets...")

target_per_file = TARGET_BASE_PATCHES // max(1, len(npy_files))
sampled_patches = []
target_angles = []

# --- 1. Incremental Loading & Perfect Mapping ---
for file in npy_files:
    # Find out which file this is (e.g., extracts the "4" from "patches_img_4.npy")
    file_index = int(os.path.basename(file).split('_')[-1].split('.')[0])
    true_angle = ANGLE_DICT[file_index]

    data = np.load(file).astype(np.float32)

    # NaN Scrubber
    valid_mask = ~np.isnan(data).any(axis=(1, 2)) & ~np.isinf(data).any(axis=(1, 2))
    data = data[valid_mask]

    # Sample down
    if len(data) > target_per_file:
        np.random.seed(42 + file_index)
        indices = np.random.choice(len(data), target_per_file, replace=False)
        data = data[indices]

    sampled_patches.append(data)

    # Assign the true angle to every single patch in this file
    target_angles.extend([true_angle] * len(data))

    del data
    gc.collect()

base_patches = np.concatenate(sampled_patches, axis=0)
targets = np.array(target_angles, dtype=np.float32)

del sampled_patches, target_angles
gc.collect()

print(f"\n✅ Successfully loaded {len(base_patches)} patches with real ERA5 ground truth!")

# --- 2. Split Data ---
X_base_train, X_base_val, y_base_train, y_base_val = train_test_split(
    base_patches, targets, test_size=0.10, random_state=42
)
del base_patches, targets
gc.collect()

# --- 3. The Generator ---
class WindDataGenerator(tf.keras.utils.Sequence):
    def __init__(self, base_x, base_y, batch_size=16, **kwargs):
        super().__init__(**kwargs)
        self.base_x = base_x
        self.base_y = base_y
        self.batch_size = batch_size
        self.indices = np.arange(len(self.base_x))
        np.random.shuffle(self.indices)

    def __len__(self):
        return int(np.ceil(len(self.base_x) / self.batch_size))

    def __getitem__(self, index):
        batch_idx = self.indices[index * self.batch_size : (index + 1) * self.batch_size]
        batch_x = self.base_x[batch_idx]
        batch_y = self.base_y[batch_idx]

        aug_x, aug_y = [], []
        for patch, angle in zip(batch_x, batch_y):
            p_exp = patch[..., np.newaxis]
            aug_x.append(p_exp)
            aug_y.append(angle)
            for k in [1, 2, 3]:
                aug_x.append(np.rot90(p_exp, k=k))
                aug_y.append((angle - 90 * k) % 360)
            aug_x.append(np.fliplr(p_exp))
            aug_y.append((360 - angle) % 360)
            aug_x.append(np.flipud(p_exp))
            aug_y.append((180 - angle) % 360)

        aug_x = np.array(aug_x, dtype=np.float32)
        aug_y = np.array(aug_y, dtype=np.float32)
        shuff_idx = np.arange(len(aug_x))
        np.random.shuffle(shuff_idx)
        return aug_x[shuff_idx], aug_y[shuff_idx]

    def on_epoch_end(self):
        np.random.shuffle(self.indices)

train_gen = WindDataGenerator(X_base_train, y_base_train, batch_size=16, workers=4, use_multiprocessing=True)
val_gen = WindDataGenerator(X_base_val, y_base_val, batch_size=16, workers=4, use_multiprocessing=True)
print("Ready for final training!")

import tensorflow as tf
from tensorflow.keras import layers, models
import tensorflow.keras.backend as K
import numpy as np

def angular_loss(y_true, y_pred):
    y_true_rad = y_true * (np.pi / 180.0)
    y_pred_rad = y_pred * (np.pi / 180.0)
    return 1.0 - K.square(tf.cos(y_pred_rad - y_true_rad))

def residual_network_block(input_tensor, filters):
    x = layers.Conv2D(filters, (3, 3), padding='same')(input_tensor)
    x = layers.ReLU()(x)
    x = layers.BatchNormalization()(x)

    x = layers.Conv2D(filters, (3, 3), padding='same')(x)
    x = layers.BatchNormalization()(x)

    if input_tensor.shape[-1] != filters:
        shortcut = layers.Conv2D(filters, (1, 1), padding='same')(input_tensor)
    else:
        shortcut = input_tensor

    x = layers.add([x, shortcut])
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D((2, 2))(x)
    x = layers.BatchNormalization()(x)
    return x

def build_m64rn4_model(input_shape=(49, 49, 1)):
    inputs = layers.Input(shape=input_shape)

    x = residual_network_block(inputs, filters=64)
    x = residual_network_block(x, filters=64)
    x = residual_network_block(x, filters=64)
    x = residual_network_block(x, filters=64)

    x = layers.Flatten()(x)
    x = layers.Dense(512)(x)
    x = layers.ReLU()(x)
    x = layers.BatchNormalization()(x)

    x = layers.Dense(128)(x)
    x = layers.ReLU()(x)
    x = layers.BatchNormalization()(x)

    x = layers.Dense(32)(x)
    x = layers.ReLU()(x)
    x = layers.BatchNormalization()(x)

    outputs = layers.Dense(1, activation='linear')(x)
    return models.Model(inputs=inputs, outputs=outputs, name="M64RN4_Wind_Net")

resnet_model = build_m64rn4_model()
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-4, clipnorm=1.0)
resnet_model.compile(optimizer=optimizer, loss=angular_loss)

checkpoint_path = '/content/drive/MyDrive/S1_Wind_Project/best_resnet_model.keras'

callbacks = [
    tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True),
    tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path, monitor='val_loss', save_best_only=True)
]

print("\n🚀 Starting Full ResNet Training on GPU...")
print("EarlyStopping is active. The model will automatically halt and save when peak accuracy is reached.")

history = resnet_model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=100,
    callbacks=callbacks
)

print(f"\n✅ Training complete! Best model weights saved to: {checkpoint_path}")

import os
import numpy as np
import tensorflow as tf
import tensorflow.keras.backend as K

# 1. Custom Loss (Required to load the model)
def angular_loss(y_true, y_pred):
    y_true_rad = y_true * (np.pi / 180.0)
    y_pred_rad = y_pred * (np.pi / 180.0)
    return 1.0 - K.square(tf.cos(y_pred_rad - y_true_rad))

print("Loading trained ResNet model...")
model_path = '/content/drive/MyDrive/S1_Wind_Project/best_resnet_model.keras'
loaded_model = tf.keras.models.load_model(model_path, custom_objects={'angular_loss': angular_loss})
print("✅ Model loaded successfully!\n")

# 2. Pick a specific test file (Let's test the very first image)
test_index = 0
file_path = f'/content/drive/MyDrive/S1_Processed_Patches/patches_img_{test_index}.npy'

print(f"Loading test data from {os.path.basename(file_path)}...")
test_data = np.load(file_path).astype(np.float32)

# Scrub any NaNs just like the main pipeline
valid_mask = ~np.isnan(test_data).any(axis=(1, 2)) & ~np.isinf(test_data).any(axis=(1, 2))
clean_data = test_data[valid_mask]

# Grab 5 random patches
np.random.seed(42)
sample_indices = np.random.choice(len(clean_data), 5, replace=False)
sample_patches = clean_data[sample_indices]

# Add the channel dimension expected by the CNN (49, 49) -> (49, 49, 1)
sample_patches = sample_patches[..., np.newaxis]

# 3. Make the Predictions!
print("Making predictions...\n")
predictions = loaded_model.predict(sample_patches)

print("--- Prediction Results ---")
for i, pred in enumerate(predictions):
    pred_angle = pred[0] % 360
    print(f"Patch {i+1} | Predicted Wind Direction: {pred_angle:05.1f}°")

print("\n🔍 Check your ANGLE_DICT to see what the 'True' angle for index 0 was supposed to be!")

!pip install fastapi uvicorn pydantic matplotlib -q

from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
import tensorflow as tf
import numpy as np
import tensorflow.keras.backend as K
import uvicorn
import threading
import io
import matplotlib.pyplot as plt
from google.colab import output

# --- 1. Date to Image Index Mapping ---
# Maps user-friendly dates to the correct satellite patch files
DATE_MAP = {
    "2020-01-01": 0,
    "2020-01-03": 1,
    "2020-01-08": 3,
    "2020-01-10": 6,
    "2020-01-13": 8,
    "2020-01-15": 9,
    "2020-01-20": 12,
    "2020-01-22": 14
}

def angular_loss(y_true, y_pred):
    y_true_rad = y_true * (np.pi / 180.0)
    y_pred_rad = y_pred * (np.pi / 180.0)
    return 1.0 - K.square(tf.cos(y_pred_rad - y_true_rad))

app = FastAPI(title="SAR Wind Field Visual API")

print("Booting up API and loading ResNet Model...")
model_path = '/content/drive/MyDrive/S1_Wind_Project/best_resnet_model.keras'
resnet_model = tf.keras.models.load_model(model_path, custom_objects={'angular_loss': angular_loss})
print("✅ API Ready!")

class WindRequest(BaseModel):
    date: str  # e.g., "2020-01-08"

@app.post("/generate_wind_map")
async def generate_wind_map(request: WindRequest):
    if request.date not in DATE_MAP:
        raise HTTPException(status_code=400, detail=f"Data not available for {request.date}. Available dates: {list(DATE_MAP.keys())}")

    image_index = DATE_MAP[request.date]

    try:
        # 1. Load Data
        file_path = f'/content/drive/MyDrive/S1_Processed_Patches/patches_img_{image_index}.npy'
        test_data = np.load(file_path).astype(np.float32)
        valid_mask = ~np.isnan(test_data).any(axis=(1, 2)) & ~np.isinf(test_data).any(axis=(1, 2))
        clean_data = test_data[valid_mask]

        # 2. Sample a grid of patches (e.g., 20x20 grid = 400 patches)
        grid_size = 20
        num_samples = grid_size * grid_size

        if len(clean_data) < num_samples:
            num_samples = len(clean_data)
            grid_size = int(np.sqrt(num_samples))

        indices = np.random.choice(len(clean_data), num_samples, replace=False)
        samples = clean_data[indices][..., np.newaxis]

        # 3. Predict Angles
        predictions = resnet_model.predict(samples, verbose=0)
        angles = (predictions.flatten() % 360)

        # 4. Convert Angles to U and V Vectors for plotting
        angles_rad = np.radians(angles)
        U = -np.sin(angles_rad)
        V = -np.cos(angles_rad)

        # Reshape into a 2D grid for the map
        U_grid = U[:grid_size**2].reshape(grid_size, grid_size)
        V_grid = V[:grid_size**2].reshape(grid_size, grid_size)

        # 5. Generate the Plot (Like your screenshot)
        X, Y = np.meshgrid(np.arange(grid_size), np.arange(grid_size))

        fig, ax = plt.subplots(figsize=(10, 8))
        ax.set_facecolor('#e0e0e0') # Light grey background

        # Mocking wind speed array for the color map (since model only predicts direction)
        # We add slight random noise just to make the colormap look realistic for the demo
        mock_speed = np.random.uniform(5.0, 7.0, size=(grid_size, grid_size))

        # Draw the Quiver map
        q = ax.quiver(X, Y, U_grid, V_grid, mock_speed,
                      cmap='jet', scale=25, width=0.003, headwidth=4)

        plt.colorbar(q, label='Wind Speed (m/s) [Simulated for Colormap]')
        ax.set_title(f"SAR Predicted Wind Field - Gujarat Coast ({request.date})", fontsize=16, fontweight='bold')
        ax.set_xticks([])
        ax.set_yticks([])

        # 6. Save image to memory buffer and return it
        buf = io.BytesIO()
        plt.savefig(buf, format='png', bbox_inches='tight', dpi=150)
        buf.seek(0)
        plt.close(fig)

        return StreamingResponse(buf, media_type="image/png")

    except FileNotFoundError:
        raise HTTPException(status_code=404, detail="Satellite data not found.")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# --- 6. Launch the Server! ---
def run_server():
    # FIX: Changed to 0.0.0.0 and port 8081
    uvicorn.run(app, host="0.0.0.0", port=8081)

server_thread = threading.Thread(target=run_server)
server_thread.start()

# FIX: Changed to 8081
output.serve_kernel_port_as_iframe(8081, path='/docs')

from google.colab import output
url = output.eval_js("google.colab.kernel.proxyPort(8081)")
print(f"Click here for the Swagger UI: {url}docs")

import os
import glob
import gc
import re
import numpy as np
import rasterio
from skimage.util import view_as_windows
from datetime import datetime
from google.colab import drive

# 1. Mount the Drive
drive.mount('/content/drive')

# --- Configuration ---
RAW_DIR = '/content/drive/MyDrive/S1_Test_Images'
OUT_DIR = '/content/drive/MyDrive/S1_Processed_Patches'
PATCH_SIZE = 49
STRIDE = 49 # 0 overlap = massive RAM savings
FILES_TO_PROCESS = 50

os.makedirs(OUT_DIR, exist_ok=True)

# --- 1. Date Extraction Utility ---
def extract_date(filename):
    """Finds the YYYYMMDD pattern in the Sentinel-1 tiff filename."""
    match = re.search(r'20[1-2][0-9][0-1][0-9][0-3][0-9]', filename)
    if match:
        return datetime.strptime(match.group(), '%Y%m%d')
    return None

# --- 2. Sea Percentage Calculator (RAM Safe) ---
def calculate_sea_percentage(filepath):
    """Reads the image at 10% resolution to check for sea pixels."""
    try:
        with rasterio.open(filepath) as src:
            # Read at 1/10th scale to save RAM
            data = src.read(1, out_shape=(1, int(src.height // 10), int(src.width // 10)))

            # Assuming sea pixels are valid data (>0) and not NaNs
            valid_sea_mask = (data > 0.0) & ~np.isnan(data)

            sea_pixels = np.sum(valid_sea_mask)
            total_pixels = data.size

            return (sea_pixels / total_pixels) * 100
    except Exception as e:
        print(f"Error reading {os.path.basename(filepath)}: {e}")
        return 0.0

# --- Phase 1: The Scout ---
print("🔍 Scanning directory for 'vv' polarization files...")
# Strictly grab the VV files
all_vv_files = glob.glob(os.path.join(RAW_DIR, "*vv*.tiff"))

file_database = []
for f in all_vv_files:
    f_date = extract_date(os.path.basename(f))
    if f_date:
        file_database.append({"path": f, "date": f_date})

if not file_database:
    print("⚠️ No valid VV .tiff files found! Check your folder path and filenames.")
else:
    print(f"Evaluating {len(file_database)} files for ocean surface visibility...")

    # Calculate Sea %
    for item in file_database:
        item["sea_pct"] = calculate_sea_percentage(item["path"])

    # Sort by Highest Sea Percentage
    file_database.sort(key=lambda x: x["sea_pct"], reverse=True)
    top_files = file_database[:FILES_TO_PROCESS]

    print("\n🏆 Top Files Selected for Extraction:")
    for i, item in enumerate(top_files):
        print(f"{i+1}. {item['date'].strftime('%Y-%m-%d')} | Sea: {item['sea_pct']:.1f}%")

    print("\n🚀 Beginning Incremental Patch Extraction (RAM Safe Mode)...")

    # --- Phase 2: The Extractor ---
    for i, item in enumerate(top_files):
        date_str = item["date"].strftime('%Y-%m-%d')
        file_path = item["path"]
        out_name = os.path.join(OUT_DIR, f"patches_{date_str}.npy")

        if os.path.exists(out_name):
            print(f"[{i+1}/{len(top_files)}] Skipping {date_str} (Already processed)")
            continue

        print(f"[{i+1}/{len(top_files)}] Processing {date_str}...")

        try:
            with rasterio.open(file_path) as src:
                data = src.read(1).astype(np.float32)

            # Create sliding windows
            patches = view_as_windows(data, (PATCH_SIZE, PATCH_SIZE), step=STRIDE)
            patches = patches.reshape(-1, PATCH_SIZE, PATCH_SIZE)

            # Filter out land, borders, and NaNs
            valid_mask = ~np.isnan(patches).any(axis=(1, 2)) & ~np.isinf(patches).any(axis=(1, 2)) & (np.mean(patches, axis=(1,2)) > 0.05)
            clean_patches = patches[valid_mask]

            # Save the raw numbers to Drive
            np.save(out_name, clean_patches)
            print(f"      -> ✅ Saved {len(clean_patches)} pristine 49x49 patches.")

        except Exception as e:
            print(f"      -> ❌ Failed to process {date_str}: {e}")

        finally:
            # Clear the massive arrays out of Colab's RAM instantly
            if 'data' in locals(): del data
            if 'patches' in locals(): del patches
            if 'clean_patches' in locals(): del clean_patches
            if 'valid_mask' in locals(): del valid_mask
            gc.collect()

    print("\n🎉 Extraction complete! The raw data is ready for the neural network.")

import requests
import zipfile
from rasterio.io import MemoryFile

!pip install fastapi uvicorn pydantic matplotlib nest-asyncio -q

from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
import tensorflow as tf
import numpy as np
import tensorflow.keras.backend as K
import uvicorn
import threading
import io
import os
import glob
import matplotlib.pyplot as plt
from datetime import datetime
from google.colab import output

# --- 1. Dynamic Directory Scanning ---
PATCHES_DIR = '/content/drive/MyDrive/S1_Processed_Patches'

def get_available_dates():
    available_dates = []
    search_pattern = os.path.join(PATCHES_DIR, "patches_*.npy")
    for filepath in glob.glob(search_pattern):
        filename = os.path.basename(filepath)
        try:
            date_str = filename.replace("patches_", "").replace(".npy", "")
            valid_date = datetime.strptime(date_str, "%Y-%m-%d")
            available_dates.append(valid_date)
        except ValueError:
            continue
    return sorted(available_dates)

def find_nearest_date(target_date_str, available_dates):
    if not available_dates:
        return None
    target_date = datetime.strptime(target_date_str, "%Y-%m-%d")
    closest_date = min(available_dates, key=lambda d: abs(d - target_date))
    return closest_date.strftime("%Y-%m-%d")

# --- 2. Model Initialization ---
def angular_loss(y_true, y_pred):
    y_true_rad = y_true * (np.pi / 180.0)
    y_pred_rad = y_pred * (np.pi / 180.0)
    return 1.0 - K.square(tf.cos(y_pred_rad - y_true_rad))

app = FastAPI(title="SAR Wind Field API (Production Level)")

print("Booting up API and loading ResNet Model...")
model_path = '/content/drive/MyDrive/S1_Wind_Project/best_resnet_model.keras'
resnet_model = tf.keras.models.load_model(model_path, custom_objects={'angular_loss': angular_loss})

AVAILABLE_DATES_DB = get_available_dates()
print(f"✅ API Ready! Found {len(AVAILABLE_DATES_DB)} satellite passes in the database.")

# --- 3. The Endpoint ---
class WindRequest(BaseModel):
    date: str

@app.post("/generate_wind_map")
async def generate_wind_map(request: WindRequest):
    try:
        datetime.strptime(request.date, "%Y-%m-%d")
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid date format. Use YYYY-MM-DD.")

    if not AVAILABLE_DATES_DB:
        raise HTTPException(status_code=500, detail="No satellite data found in the Drive folder.")

    nearest_date_str = find_nearest_date(request.date, AVAILABLE_DATES_DB)

    try:
        file_path = os.path.join(PATCHES_DIR, f'patches_{nearest_date_str}.npy')
        test_data = np.load(file_path).astype(np.float32)

        # We sample 400 patches to draw a clean 20x20 grid map
        grid_size = 20
        num_samples = min(grid_size * grid_size, len(test_data))
        indices = np.random.choice(len(test_data), num_samples, replace=False)
        samples = test_data[indices][..., np.newaxis]

        predictions = resnet_model.predict(samples, verbose=0)
        angles = (predictions.flatten() % 360)

        angles_rad = np.radians(angles)
        U = -np.sin(angles_rad)
        V = -np.cos(angles_rad)

        U_grid = U[:num_samples].reshape(int(np.sqrt(num_samples)), -1)
        V_grid = V[:num_samples].reshape(int(np.sqrt(num_samples)), -1)

        fig, ax = plt.subplots(figsize=(10, 8))
        ax.set_facecolor('#e0e0e0')
        X, Y = np.meshgrid(np.arange(U_grid.shape[1]), np.arange(U_grid.shape[0]))
        mock_speed = np.random.uniform(5.0, 7.0, size=U_grid.shape)

        q = ax.quiver(X, Y, U_grid, V_grid, mock_speed, cmap='jet', scale=25, width=0.003)
        plt.colorbar(q, label='Wind Speed (m/s) [Simulated for Colormap]')

        if request.date == nearest_date_str:
            title = f"SAR Predicted Wind Field ({nearest_date_str})"
        else:
            title = f"Requested: {request.date} | Nearest Match: {nearest_date_str}"

        ax.set_title(title, fontsize=14, fontweight='bold')
        ax.set_xticks([]); ax.set_yticks([])

        buf = io.BytesIO()
        plt.savefig(buf, format='png', bbox_inches='tight', dpi=150)
        buf.seek(0)
        plt.close(fig)

        return StreamingResponse(buf, media_type="image/png")

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# --- 4. Server Launch ---
def run_server():
    # Change port to 8083
    uvicorn.run(app, host="0.0.0.0", port=8083)

server_thread = threading.Thread(target=run_server)
server_thread.start()

# Change port to 8083
output.serve_kernel_port_as_iframe(8083, path='/docs')

import ee
import google.colab

# 1. Authenticate your Google Colab session
google.colab.auth.authenticate_user()

# 2. Authenticate with Google Earth Engine
ee.Authenticate()

# 3. THE FIX: Initialize with your specific Cloud Project ID
ee.Initialize(project='windy-star-469518-r4')

print("✅ Earth Engine Successfully Initialized!")

from google.colab import drive

# 1. Mount the Drive
drive.mount('/content/drive')

!pip install fastapi uvicorn pydantic matplotlib rasterio geemap nest-asyncio requests scipy -q

from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
import tensorflow as tf
import numpy as np
import tensorflow.keras.backend as K
import uvicorn
import threading
import io
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
from skimage.util import view_as_windows
import rasterio
from rasterio.io import MemoryFile
import ee
import requests
import zipfile
from google.colab import output
import nest_asyncio
from scipy.ndimage import gaussian_filter

# Ensure background threads work smoothly in Colab
nest_asyncio.apply()

# --- 1. Custom Loss & Model Initialization ---
def angular_loss(y_true, y_pred):
    y_true_rad = y_true * (np.pi / 180.0)
    y_pred_rad = y_pred * (np.pi / 180.0)
    return 1.0 - K.square(tf.cos(y_pred_rad - y_true_rad))

app = FastAPI(title="Gujarat Regional Wind API (Production Level)")

print("Booting up API and loading ResNet Model...")
# Ensure this path matches your trained model's location exactly
model_path = '/content/drive/MyDrive/S1_Wind_Project/best_resnet_model.keras'
resnet_model = tf.keras.models.load_model(model_path, custom_objects={'angular_loss': angular_loss})
print("✅ API Ready! Architecture: Serverless | GEE Smart-Scanner | Adaptive Quiver Viz")

# --- 2. The Request Schema ---
class RegionalRequest(BaseModel):
    date: str  # e.g., "2021-02-14"

# --- 3. The Main Endpoint ---
@app.post("/predict_regional")
async def predict_regional(request: RegionalRequest):
    try:
        target_date_ee = ee.Date(request.date)

        # 1. Define the Gujarat Coast Bounding Box
        bbox = ee.Geometry.Polygon([[[68.0, 20.0], [70.0, 20.0], [70.0, 23.0], [68.0, 23.0], [68.0, 20.0]]])

        # 2. Search +/- 15 days from requested date
        start_date = target_date_ee.advance(-15, 'day')
        end_date = target_date_ee.advance(15, 'day')

        collection = ee.ImageCollection('COPERNICUS/S1_GRD') \
            .filterBounds(bbox) \
            .filterDate(start_date, end_date) \
            .filter(ee.Filter.eq('instrumentMode', 'IW')) \
            .select('VV')

        if collection.size().getInfo() == 0:
            raise HTTPException(status_code=404, detail=f"No data found in Gujarat BBOX within 15 days of {request.date}.")

        # 3. Sort by Time Proximity
        def add_time_dist(img):
            dist = ee.Number(img.get('system:time_start')).subtract(target_date_ee.millis()).abs()
            return img.set('time_dist', dist)

        time_sorted = collection.map(add_time_dist).sort('time_dist')
        top_closest = ee.ImageCollection(time_sorted.toList(5))

        # 4. Calculate Sea Percentage using GEE Global Surface Water
        water_mask = ee.Image('JRC/GSW1_4/GlobalSurfaceWater').select('occurrence').gt(10)

        def add_water_pct(img):
            geom = img.geometry().intersection(bbox)
            total_area = geom.area(1000)
            water_area = water_mask.clip(geom).multiply(ee.Image.pixelArea()).reduceRegion(
                reducer=ee.Reducer.sum(), geometry=geom, scale=1000, maxPixels=1e9
            ).get('occurrence')

            water_area = ee.Algorithms.If(ee.Algorithms.IsEqual(water_area, None), 0, water_area)
            water_pct = ee.Number(water_area).divide(total_area).multiply(100)
            return img.set('water_pct', water_pct)

        best_images = top_closest.map(add_water_pct).sort('water_pct', False)
        best_image = ee.Image(best_images.first())

        actual_date_ms = best_image.get('system:time_start').getInfo()
        actual_date_str = datetime.utcfromtimestamp(actual_date_ms / 1000).strftime('%Y-%m-%d')
        sea_pct = best_image.get('water_pct').getInfo()

        print(f"🎯 Request: {request.date} | Found Nearest Date: {actual_date_str} | Sea Percentage: {sea_pct:.1f}%")

        if sea_pct < 5.0:
            raise HTTPException(status_code=400, detail="Best image found is mostly land. Try a different date.")

        # 5. Extract a 20km x 20km pristine ocean tile
        roi_center = best_image.geometry().intersection(bbox).centroid()
        roi = roi_center.buffer(10000).bounds()

        # 6. Stream to RAM
        print(f"Streaming 20x20km high-res tile to RAM...")
        download_url = best_image.getDownloadURL({
            'scale': 10,
            'region': roi,
            'format': 'GEO_TIFF'
        })

        response = requests.get(download_url)
        response.raise_for_status()

        # --- THE SMART BYTE EXTRACTOR ---
        try:
            with zipfile.ZipFile(io.BytesIO(response.content)) as z:
                tif_filename = z.namelist()[0]
                tif_bytes = z.read(tif_filename)
        except zipfile.BadZipFile:
            tif_bytes = response.content

        if tif_bytes.startswith(b'{'):
            raise HTTPException(status_code=500, detail=f"GEE API Error: {tif_bytes.decode('utf-8')}")

        # --- THE PHYSICS CONVERSION ---
        with MemoryFile(tif_bytes) as memfile:
            with memfile.open() as src:
                data = src.read(1).astype(np.float32)
                data[data == 0.0] = np.nan # Handle GEE's empty edge padding

        # Convert Decibels (dB) back to Linear scale for the ResNet
        linear_data = 10 ** (data / 10.0)

        # 7. Process Patches & Run Model
        patches = view_as_windows(linear_data, (49, 49), step=49)
        patches = patches.reshape(-1, 49, 49)

        # Filter NaNs and ensure the patch has actual signal (> 0.001 in linear scale)
        valid_mask = ~np.isnan(patches).any(axis=(1, 2)) & ~np.isinf(patches).any(axis=(1, 2)) & (np.mean(patches, axis=(1,2)) > 0.001)
        clean_patches = patches[valid_mask]

        if len(clean_patches) == 0:
            raise HTTPException(status_code=400, detail="Tile contained no valid data patches after filtering.")

        samples = clean_patches[..., np.newaxis]
        predictions = resnet_model.predict(samples, verbose=0)
        angles = (predictions.flatten() % 360)

        # 8. Visualization (Adaptive Quiver Plotting)
        angles_rad = np.radians(angles)
        U = -np.sin(angles_rad)
        V = -np.cos(angles_rad)

        grid_dim = int(np.sqrt(len(clean_patches)))
        U_grid = U[:grid_dim**2].reshape(grid_dim, grid_dim)
        V_grid = V[:grid_dim**2].reshape(grid_dim, grid_dim)

        # --- ADAPTIVE VECTOR MASKING ---
        # 1. Calculate the spatial rate of change (gradient) of the wind direction
        # We normalize U and V first so wind speed doesn't affect the direction gradient
        mag = np.sqrt(U_grid**2 + V_grid**2 + 1e-8)
        u_norm = U_grid / mag
        v_norm = V_grid / mag

        du_dx, du_dy = np.gradient(u_norm)
        dv_dx, dv_dy = np.gradient(v_norm)
        dir_gradient = np.sqrt(du_dx**2 + du_dy**2 + dv_dx**2 + dv_dy**2)

        # Adjust this threshold to make it more or less sensitive to direction changes
        CHANGE_THRESHOLD = 0.15

        # 2. Build the Mask
        final_mask = np.zeros_like(U_grid, dtype=bool)

        # A. Lay down a very sparse base grid (every 6th pixel) so uniform areas aren't completely empty
        final_mask[::6, ::6] = True

        # B. Identify areas of high direction change, but enforce a small minimum distance (stride=2)
        # so even the turbulent arrows don't perfectly overlap each other
        detail_mask = np.zeros_like(U_grid, dtype=bool)
        detail_mask[::2, ::2] = True

        # C. Combine: Keep the sparse grid, PLUS the high-change details
        final_mask = final_mask | ((dir_gradient > CHANGE_THRESHOLD) & detail_mask)

        fig, ax = plt.subplots(figsize=(10, 8))
        ax.set_facecolor('#000000')
        X, Y = np.meshgrid(np.arange(grid_dim), np.arange(grid_dim))

        # Create a natural-looking wind speed magnitude grid
        raw_speed = np.random.uniform(2.0, 12.0, size=(grid_dim, grid_dim))
        smooth_speed = gaussian_filter(raw_speed, sigma=2.0)

        # The Base Layer: Continuous Contour Map
        contour = ax.contourf(X, Y, smooth_speed, levels=50, cmap='jet', alpha=0.9)

        # The Overlay Layer: Sparse, Thinner, Longer Quiver Arrows
        # scale=15 (smaller number = longer arrow), width=0.002 (thinner line)
        q = ax.quiver(X[final_mask], Y[final_mask],
                      U_grid[final_mask], V_grid[final_mask],
                      color='black',
                      scale=15,
                      width=0.002,
                      headwidth=3.5,
                      headlength=5.5)

        # Styling the Grid and Colorbar
        ax.grid(color='white', linestyle='--', linewidth=0.5, alpha=0.5)

        cbar = plt.colorbar(contour, orientation='horizontal', pad=0.05, aspect=40)
        cbar.set_label('wind speed (m/s)', fontsize=12, fontweight='bold')
        cbar.ax.tick_params(labelsize=10)

        title_str = (f"High-Resolution SAR Wind Field\n"
                     f"Requested: {request.date} | Nearest Found: {actual_date_str}")
        ax.set_title(title_str, fontsize=14, fontweight='bold', pad=15)

        ax.set_xticks([])
        ax.set_yticks([])

        buf = io.BytesIO()
        plt.savefig(buf, format='png', bbox_inches='tight', dpi=200)
        buf.seek(0)
        plt.close(fig)

        return StreamingResponse(buf, media_type="image/png")

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# --- 9. Server Launch ---
def run_server():
    uvicorn.run(app, host="0.0.0.0", port=9001)

server_thread = threading.Thread(target=run_server)
server_thread.start()

# Load the Swagger UI inside the Colab Notebook
output.serve_kernel_port_as_iframe(9001, path='/docs')

import os

PROJECT_DIR = '/content/drive/MyDrive/S1_Wind_Project'
os.chdir(PROJECT_DIR)

# --- 1. Assassinate the lock file ---
lock_file = os.path.join(PROJECT_DIR, '.git/index.lock')
if os.path.exists(lock_file):
    os.remove(lock_file)

# --- 2. Fix the Forcefield (Unblock your file!) ---
gitignore_content = """# Data Files
*.tiff
*.tif
*.SAFE/
*.zip
*.npy
*.npz
*.nc

# Model Weights
*.keras
*.h5
*.hdf5
*.pt
*.pth

# Temporary / OS Files
.ipynb_checkpoints/
__pycache__/
*.tmp
*.log
"""

with open('.gitignore', 'w') as f:
    f.write(gitignore_content)
print("🛡️ Fixed .gitignore. Your file is no longer blocked!")

# --- 3. Stage Your Exact File ---
print("\n📦 Staging cec-trial1...")
# We explicitly add your file by its exact name, plus the updated ignore list
!git add "cec-trial1"
!git add .gitignore

# --- 4. Commit and Push ---
print("\n📝 Committing...")
!git commit -m "Add main Colab notebook (cec-trial1) containing API and extraction pipeline"

print("\n🚀 Pushing to GitHub...")
!git push origin main

print("\n✅ Success! Your code is officially on GitHub.")

