# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1spA8N1C1ySmqWCw5bdbk_8j7VbpT5tH-
"""

import os
import glob
import rasterio
import numpy as np
from scipy import ndimage
import gc

# --- Configuration (Relative Paths) ---
INPUT_DIR = './data/raw'
OUTPUT_DIR = './data/processed'
os.makedirs(OUTPUT_DIR, exist_ok=True)

TARGET_IMAGES = 15
PATCH_SIZE = 49
STRIDE = 20

def extract_and_clean_patches(vv_data, water_mask):
    """Slices the array into 49x49 patches and cleans land pixels."""
    h, w = vv_data.shape
    file_patches = []

    for y in range(0, h - PATCH_SIZE, STRIDE):
        for x in range(0, w - PATCH_SIZE, STRIDE):
            patch_vv = vv_data[y:y+PATCH_SIZE, x:x+PATCH_SIZE]
            patch_water = water_mask[y:y+PATCH_SIZE, x:x+PATCH_SIZE]

            land_percentage = np.sum(patch_water == 0) / (PATCH_SIZE * PATCH_SIZE)

            if land_percentage > 0.25:
                continue

            if 0.0 < land_percentage <= 0.25:
                invalid = (patch_water == 0)
                indices = ndimage.distance_transform_edt(invalid, return_distances=False, return_indices=True)
                patch_vv[invalid] = patch_vv[tuple(indices[:, invalid])]
                patch_vv[invalid] += np.random.normal(0, 0.1, np.sum(invalid))

            mean_val, std_val = np.mean(patch_vv), np.std(patch_vv)
            norm_patch = (patch_vv - mean_val) / (std_val + 1e-8)
            file_patches.append(norm_patch.astype(np.float32))

    return file_patches

if __name__ == "__main__":
    all_tifs = glob.glob(os.path.join(INPUT_DIR, "*.tif"))
    print(f"Scanning for {TARGET_IMAGES} valid images in {INPUT_DIR}...")

    successful_images = 0

    for tiff_path in all_tifs:
        if successful_images >= TARGET_IMAGES:
            print("\n✅ Target reached! All necessary data is processed.")
            break

        try:
            with rasterio.open(tiff_path) as src:
                vv_data = src.read(1)
                water_mask = src.read(2)

            sea_ratio = np.sum(water_mask == 1) / water_mask.size

            if sea_ratio > 0.15:
                print(f"Processing {os.path.basename(tiff_path)} (Sea: {sea_ratio*100:.1f}%)")
                patches = extract_and_clean_patches(vv_data, water_mask)

                if len(patches) > 0:
                    save_path = os.path.join(OUTPUT_DIR, f'patches_img_{successful_images}.npy')
                    np.save(save_path, np.array(patches))
                    print(f"  -> Saved {len(patches)} patches.")
                    successful_images += 1

                del patches, vv_data, water_mask
                gc.collect()

        except Exception as e:
            print(f"Failed processing {tiff_path}: {e}")

    if successful_images < TARGET_IMAGES:
        print(f"\n⚠️ Finished scanning all files, but only found {successful_images} valid images.")