# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1spA8N1C1ySmqWCw5bdbk_8j7VbpT5tH-
"""

import os
import glob
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
import tensorflow.keras.backend as K
from sklearn.model_selection import train_test_split
import gc

# --- Configuration ---
INPUT_DIR = './data/processed'
MODEL_DIR = './models'
MODEL_PATH = os.path.join(MODEL_DIR, 'best_resnet_model.keras')
os.makedirs(MODEL_DIR, exist_ok=True)

TARGET_BASE_PATCHES = 78000

# True physical wind angles from ERA5 dataset mapping
ANGLE_DICT = {
    0: 26.92, 1: 25.28, 2: 25.28, 3: 16.99, 4: 25.28,
    5: 16.99, 6: 38.82, 7: 16.99, 8: 260.79, 9: 47.87,
    10: 47.87, 11: 47.87, 12: 52.43, 13: 52.43, 14: 35.51
}

# --- Custom Loss ---
def angular_loss(y_true, y_pred):
    y_true_rad = y_true * (np.pi / 180.0)
    y_pred_rad = y_pred * (np.pi / 180.0)
    return 1.0 - K.square(tf.cos(y_pred_rad - y_true_rad))

# --- Model Architecture ---
def residual_network_block(input_tensor, filters):
    x = layers.Conv2D(filters, (3, 3), padding='same')(input_tensor)
    x = layers.ReLU()(x)
    x = layers.BatchNormalization()(x)
    x = layers.Conv2D(filters, (3, 3), padding='same')(x)
    x = layers.BatchNormalization()(x)

    if input_tensor.shape[-1] != filters:
        shortcut = layers.Conv2D(filters, (1, 1), padding='same')(input_tensor)
    else:
        shortcut = input_tensor

    x = layers.add([x, shortcut])
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D((2, 2))(x)
    x = layers.BatchNormalization()(x)
    return x

def build_m64rn4_model(input_shape=(49, 49, 1)):
    inputs = layers.Input(shape=input_shape)
    x = residual_network_block(inputs, filters=64)
    x = residual_network_block(x, filters=64)
    x = residual_network_block(x, filters=64)
    x = residual_network_block(x, filters=64)
    x = layers.Flatten()(x)
    x = layers.Dense(512)(x)
    x = layers.ReLU()(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dense(128)(x)
    x = layers.ReLU()(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dense(32)(x)
    x = layers.ReLU()(x)
    x = layers.BatchNormalization()(x)
    outputs = layers.Dense(1, activation='linear')(x)
    return models.Model(inputs=inputs, outputs=outputs, name="M64RN4_Wind_Net")

# --- Data Generator ---
class WindDataGenerator(tf.keras.utils.Sequence):
    def __init__(self, base_x, base_y, batch_size=16, **kwargs):
        super().__init__(**kwargs)
        self.base_x = base_x
        self.base_y = base_y
        self.batch_size = batch_size
        self.indices = np.arange(len(self.base_x))
        np.random.shuffle(self.indices)

    def __len__(self):
        return int(np.ceil(len(self.base_x) / self.batch_size))

    def __getitem__(self, index):
        batch_idx = self.indices[index * self.batch_size : (index + 1) * self.batch_size]
        batch_x = self.base_x[batch_idx]
        batch_y = self.base_y[batch_idx]

        aug_x, aug_y = [], []
        for patch, angle in zip(batch_x, batch_y):
            p_exp = patch[..., np.newaxis]
            aug_x.append(p_exp)
            aug_y.append(angle)
            for k in [1, 2, 3]:
                aug_x.append(np.rot90(p_exp, k=k))
                aug_y.append((angle - 90 * k) % 360)
            aug_x.append(np.fliplr(p_exp))
            aug_y.append((360 - angle) % 360)
            aug_x.append(np.flipud(p_exp))
            aug_y.append((180 - angle) % 360)

        aug_x = np.array(aug_x, dtype=np.float32)
        aug_y = np.array(aug_y, dtype=np.float32)
        shuff_idx = np.arange(len(aug_x))
        np.random.shuffle(shuff_idx)
        return aug_x[shuff_idx], aug_y[shuff_idx]

    def on_epoch_end(self):
        np.random.shuffle(self.indices)

if __name__ == "__main__":
    npy_files = glob.glob(os.path.join(INPUT_DIR, "*.npy"))
    print(f"Loading {len(npy_files)} files and applying physics targets...")

    target_per_file = TARGET_BASE_PATCHES // max(1, len(npy_files))
    sampled_patches, target_angles = [], []

    for file in npy_files:
        try:
            file_index = int(os.path.basename(file).split('_')[-1].split('.')[0])
            true_angle = ANGLE_DICT[file_index]
        except (ValueError, KeyError):
            continue # Skip files not in the dict

        data = np.load(file).astype(np.float32)
        valid_mask = ~np.isnan(data).any(axis=(1, 2)) & ~np.isinf(data).any(axis=(1, 2))
        data = data[valid_mask]

        if len(data) > target_per_file:
            np.random.seed(42 + file_index)
            indices = np.random.choice(len(data), target_per_file, replace=False)
            data = data[indices]

        sampled_patches.append(data)
        target_angles.extend([true_angle] * len(data))
        del data
        gc.collect()

    base_patches = np.concatenate(sampled_patches, axis=0)
    targets = np.array(target_angles, dtype=np.float32)
    del sampled_patches, target_angles
    gc.collect()

    X_train, X_val, y_train, y_val = train_test_split(base_patches, targets, test_size=0.10, random_state=42)
    del base_patches, targets
    gc.collect()

    train_gen = WindDataGenerator(X_train, y_train, batch_size=16, workers=4, use_multiprocessing=True)
    val_gen = WindDataGenerator(X_val, y_val, batch_size=16, workers=4, use_multiprocessing=True)

    resnet_model = build_m64rn4_model()
    optimizer = tf.keras.optimizers.Adam(learning_rate=1e-4, clipnorm=1.0)
    resnet_model.compile(optimizer=optimizer, loss=angular_loss)

    callbacks = [
        tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True),
        tf.keras.callbacks.ModelCheckpoint(filepath=MODEL_PATH, monitor='val_loss', save_best_only=True)
    ]

    print("\n🚀 Starting Full ResNet Training...")
    resnet_model.fit(train_gen, validation_data=val_gen, epochs=100, callbacks=callbacks)
    print(f"\n✅ Training complete! Best weights saved to: {MODEL_PATH}")